"""
Routine wrapping and Fortran wrapper generation for derived types.

Copyright 2024 -- present NumPy Developers.
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.

NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
"""

import os

from .auxfuncs import (
    get_type_members,
    hasbody,
    isallocatable,
    isfunction,
    isroutine,
    outmess,
)

from ._dt_helpers import (
    _C_TO_NPY_ENUM,
    _C_TO_PYFORMAT,
    _C_TO_PYOBJ,
    _PYOBJ_TO_C,
    _can_wrap_bindc,
    _can_wrap_opaque,
    _fortran_sym,
    _get_all_members,
    _get_array_dims,
    _get_char_len,
    _get_extends_parent,
    _get_member_ctype,
    _get_member_isoc_type,
    _get_alloc_ndim,
    _get_pointer_ndim,
    _is_allocatable_member,
    _is_array_member,
    _is_pointer_member,
    _is_char_member,
    _is_type_array_member,
    _is_type_member,
)

from ._dt_codegen import (
    _gen_operator_fortran_wrappers,
    _scan_operator_interfaces,
)


def generate_fortran_wrappers(modulename, type_blocks, routines=None,
                              module_block=None):
    """Generate Fortran wrapper source code for opaque pointer types,
    routines with derived type arguments, and operator implementations.

    Returns the complete Fortran source as a string, or None if no
    wrappers are needed.
    """
    # Multi-pass type resolution (same as buildhooks)
    type_map = {}
    remaining = list(type_blocks)
    for _ in range(len(type_blocks) + 1):
        if not remaining:
            break
        still_remaining = []
        for tb in remaining:
            tname = tb['name'].lower()
            if (_can_wrap_bindc(tb, type_map)
                    or _can_wrap_opaque(tb, type_map)):
                type_map[tname] = tb
            else:
                still_remaining.append(tb)
        if len(still_remaining) == len(remaining):
            break
        remaining = still_remaining

    opaque_types = [tb for tb in type_blocks
                    if _can_wrap_opaque(tb, type_map)]

    # Find routines needing wrappers
    routine_wrappers = []
    if routines:
        for routine in routines:
            if _has_derived_type_args(routine):
                wrapper_name, fortran_code = _gen_routine_fortran_wrapper(
                    modulename, routine, type_map)
                if fortran_code is not None:
                    routine_wrappers.append(fortran_code)

    # Find operator wrappers needed
    operator_wrappers = []
    if module_block and type_map:
        for tb in type_blocks:
            typename = tb['name']
            if typename.lower() not in type_map:
                continue
            ops = _scan_operator_interfaces(
                module_block, typename, type_map)
            if ops:
                op_lines = _gen_operator_fortran_wrappers(
                    typename, ops, type_map)
                if op_lines:
                    operator_wrappers.extend(op_lines)

    if not opaque_types and not routine_wrappers and not operator_wrappers:
        return None

    lines = []
    lines.append('! Auto-generated by f2py: derived type opaque pointer wrappers')
    lines.append(f'module f2py_{modulename}_derived_wrappers')
    lines.append(f'  use {modulename}')
    lines.append('  use iso_c_binding')
    lines.append('  implicit none')
    lines.append('')

    lines.append('contains')
    lines.append('')

    for tb in opaque_types:
        typename = tb['name']
        # For types with extends(parent), include all inherited members
        parent_name = _get_extends_parent(tb)
        if parent_name and parent_name in type_map:
            from collections import OrderedDict
            parent_members, own_members = _get_all_members(
                tb, type_map)
            members = OrderedDict()
            members.update(parent_members)
            members.update(own_members)
        else:
            members = get_type_members(tb)

        # Constructor: allocate + populate + return c_ptr
        # (scalar members only; arrays are zero-initialized by allocate)
        args = []
        decls = []
        assigns = []
        for mname, mvar in members.items():
            if (_is_array_member(mvar) or _is_type_member(mvar)
                    or _is_type_array_member(mvar) or _is_char_member(mvar)
                    or _is_allocatable_member(mvar)
                    or _is_pointer_member(mvar)):
                continue  # arrays, nested types, chars, allocs, ptrs skip ctor
            isoc_type = _get_member_isoc_type(mvar)
            if isoc_type is None:
                continue
            args.append(mname)
            decls.append(f'    {isoc_type}, intent(in), value :: {mname}')
            assigns.append(f'    obj%{mname} = {mname}')

        args_str = ', '.join(args)
        decls_str = '\n'.join(decls)
        assigns_str = '\n'.join(assigns)

        lines.append(
            f'  function f2py_create_{typename}({args_str}) '
            f'result(cptr) bind(c)')
        lines.append(f'    type(c_ptr) :: cptr')
        lines.append(decls_str)
        lines.append(f'    type({typename}), pointer :: obj')
        lines.append(f'    allocate(obj)')
        # Zero-initialize all members (arrays default to 0 from allocate)
        for mname, mvar in members.items():
            if _is_type_array_member(mvar):
                inner = mvar.get('typename', '').lower()
                inner_tb = type_map.get(inner)
                if inner_tb:
                    dims = _get_array_dims(mvar)
                    total = 1
                    for d in dims:
                        total *= d
                    for idx in range(1, total + 1):
                        for imname, imvar in get_type_members(
                                inner_tb).items():
                            if not _is_array_member(imvar):
                                lines.append(
                                    f'    obj%{mname}({idx})%'
                                    f'{imname} = 0')
            elif _is_type_member(mvar):
                inner = mvar.get('typename', '').lower()
                inner_tb = type_map.get(inner)
                if inner_tb:
                    for imname, imvar in get_type_members(
                            inner_tb).items():
                        if not _is_array_member(imvar):
                            lines.append(
                                f'    obj%{mname}%{imname} = 0')
            elif _is_char_member(mvar):
                lines.append(f'    obj%{mname} = \' \'')
        lines.append(assigns_str)
        lines.append(f'    cptr = c_loc(obj)')
        lines.append(f'  end function f2py_create_{typename}')
        lines.append('')

        # Destructor
        lines.append(
            f'  subroutine f2py_destroy_{typename}(cptr) bind(c)')
        lines.append(f'    type(c_ptr), value :: cptr')
        lines.append(f'    type({typename}), pointer :: obj')
        lines.append(f'    call c_f_pointer(cptr, obj)')
        lines.append(f'    deallocate(obj)')
        lines.append(f'  end subroutine f2py_destroy_{typename}')
        lines.append('')

        # Getters and setters for each member
        for mname, mvar in members.items():
            if _is_type_array_member(mvar):
                inner = mvar.get('typename', '').lower()
                # Array of types: indexed getter (1-based)
                lines.append(
                    f'  function f2py_get_{typename}_{mname}'
                    f'(cptr, idx) '
                    f'result(inner_cptr) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    integer(c_int), value :: idx')
                lines.append(f'    type(c_ptr) :: inner_cptr')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(
                    f'    type({inner}), pointer :: inner_obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(f'    allocate(inner_obj)')
                lines.append(
                    f'    inner_obj = obj%{mname}(idx)')
                lines.append(
                    f'    inner_cptr = c_loc(inner_obj)')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}')
                lines.append('')

                # Array of types: indexed setter (1-based)
                lines.append(
                    f'  subroutine f2py_set_{typename}_{mname}'
                    f'(cptr, idx, inner_cptr) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    integer(c_int), value :: idx')
                lines.append(
                    f'    type(c_ptr), value :: inner_cptr')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(
                    f'    type({inner}), pointer :: inner_obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    call c_f_pointer(inner_cptr, inner_obj)')
                lines.append(
                    f'    obj%{mname}(idx) = inner_obj')
                lines.append(
                    f'  end subroutine f2py_set_{typename}_{mname}')
                lines.append('')
                continue

            if _is_type_member(mvar):
                inner = mvar.get('typename', '').lower()
                # Nested type getter: allocate copy, return c_ptr
                lines.append(
                    f'  function f2py_get_{typename}_{mname}(cptr) '
                    f'result(inner_cptr) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(f'    type(c_ptr) :: inner_cptr')
                lines.append(f'    type({typename}), pointer :: obj')
                lines.append(f'    type({inner}), pointer :: inner_obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(f'    allocate(inner_obj)')
                lines.append(f'    inner_obj = obj%{mname}')
                lines.append(f'    inner_cptr = c_loc(inner_obj)')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}')
                lines.append('')

                # Nested type setter: copy from inner c_ptr
                lines.append(
                    f'  subroutine f2py_set_{typename}_{mname}'
                    f'(cptr, inner_cptr) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(f'    type(c_ptr), value :: inner_cptr')
                lines.append(f'    type({typename}), pointer :: obj')
                lines.append(f'    type({inner}), pointer :: inner_obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    call c_f_pointer(inner_cptr, inner_obj)')
                lines.append(f'    obj%{mname} = inner_obj')
                lines.append(
                    f'  end subroutine f2py_set_{typename}_{mname}')
                lines.append('')
                continue

            if _is_char_member(mvar):
                char_len = _get_char_len(mvar)
                # Character getter: copies member into C buffer
                lines.append(
                    f'  subroutine f2py_get_{typename}_{mname}'
                    f'(cptr, buf, buflen) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    integer(c_int), value :: buflen')
                lines.append(
                    f'    character(c_char), intent(out) :: buf(buflen)')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    integer :: i')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    do i = 1, min(buflen, '
                    f'len_trim(obj%{mname}))')
                lines.append(
                    f'      buf(i) = obj%{mname}(i:i)')
                lines.append(f'    end do')
                lines.append(
                    f'    do i = len_trim(obj%{mname})+1, buflen')
                lines.append(f'      buf(i) = \' \'')
                lines.append(f'    end do')
                lines.append(
                    f'  end subroutine f2py_get_{typename}_{mname}')
                lines.append('')

                # Character setter: copies C buffer into member
                lines.append(
                    f'  subroutine f2py_set_{typename}_{mname}'
                    f'(cptr, buf, buflen) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    integer(c_int), value :: buflen')
                lines.append(
                    f'    character(c_char), intent(in) :: buf(buflen)')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    integer :: i, copy_len')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(f'    obj%{mname} = \' \'')
                lines.append(
                    f'    copy_len = min(buflen, len(obj%{mname}))')
                lines.append(f'    do i = 1, copy_len')
                lines.append(
                    f'      obj%{mname}(i:i) = buf(i)')
                lines.append(f'    end do')
                lines.append(
                    f'  end subroutine f2py_set_{typename}_{mname}')
                lines.append('')
                continue

            if _is_allocatable_member(mvar):
                isoc_type = _get_member_isoc_type(mvar)
                if isoc_type is None:
                    continue
                ndim = _get_alloc_ndim(mvar)

                # _allocated: returns logical(c_bool)
                # Uses Fortran allocated() intrinsic (F2018 16.9.3)
                lines.append(
                    f'  function f2py_get_{typename}_{mname}'
                    f'_allocated(cptr) '
                    f'result(is_alloc) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    logical(c_bool) :: is_alloc')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    is_alloc = allocated(obj%{mname})')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}'
                    f'_allocated')
                lines.append('')

                # _ndim: returns rank as integer(c_int)
                # Uses Fortran rank intrinsic concept (known at
                # compile time from the type declaration)
                lines.append(
                    f'  function f2py_get_{typename}_{mname}'
                    f'_ndim(cptr) '
                    f'result(array_rank) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    integer(c_int) :: array_rank')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    array_rank = {ndim}')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}'
                    f'_ndim')
                lines.append('')

                # _shape: fills caller-provided array with
                # size(member, dim) for each dimension
                # Uses Fortran size() intrinsic (F2018 16.9.182)
                lines.append(
                    f'  subroutine f2py_get_{typename}_{mname}'
                    f'_shape(cptr, shape_out) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    integer(c_int) :: shape_out({ndim})')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(
                    f'    integer :: dim_idx')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    if (allocated(obj%{mname})) then')
                for dim_idx in range(1, ndim + 1):
                    lines.append(
                        f'      shape_out({dim_idx}) = '
                        f'size(obj%{mname}, {dim_idx})')
                lines.append(f'    else')
                for dim_idx in range(1, ndim + 1):
                    lines.append(
                        f'      shape_out({dim_idx}) = 0')
                lines.append(f'    end if')
                lines.append(
                    f'  end subroutine f2py_get_{typename}_{mname}'
                    f'_shape')
                lines.append('')

                # _data: returns type(c_ptr) to contiguous array data
                # F2018 18.2.3.3: c_loc on allocatable requires
                # TARGET attribute or allocatable (F2008+)
                lines.append(
                    f'  function f2py_get_{typename}_{mname}'
                    f'_data(cptr) '
                    f'result(data_ptr) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(f'    type(c_ptr) :: data_ptr')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    if (allocated(obj%{mname})) then')
                lines.append(
                    f'      data_ptr = c_loc(obj%{mname})')
                lines.append(f'    else')
                lines.append(f'      data_ptr = c_null_ptr')
                lines.append(f'    end if')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}'
                    f'_data')
                lines.append('')

                # setter: deallocate if allocated, allocate with
                # per-dimension sizes, copy data from C pointer
                # F2018 9.7.1.2: deallocate statement
                # F2018 9.7.1.1: allocate statement with shape
                dim_args = ', '.join(
                    f'dim_{idx}' for idx in range(1, ndim + 1))
                dim_decls = ', '.join(
                    f'dim_{idx}' for idx in range(1, ndim + 1))
                alloc_shape = ', '.join(
                    f'dim_{idx}' for idx in range(1, ndim + 1))
                colon_shape = ', '.join([':'] * ndim)
                cf_shape = ', '.join(
                    f'dim_{idx}' for idx in range(1, ndim + 1))

                lines.append(
                    f'  subroutine f2py_set_{typename}_{mname}'
                    f'(cptr, {dim_args}, src) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                for idx in range(1, ndim + 1):
                    lines.append(
                        f'    integer(c_int), value :: dim_{idx}')
                lines.append(f'    type(c_ptr), value :: src')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(
                    f'    {isoc_type}, pointer :: '
                    f'src_arr({colon_shape})')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    if (allocated(obj%{mname})) '
                    f'deallocate(obj%{mname})')
                # Check first dimension > 0 as sentinel for
                # "deallocate only" calls (all dims = 0)
                lines.append(f'    if (dim_1 > 0) then')
                lines.append(
                    f'      allocate(obj%{mname}'
                    f'({alloc_shape}))')
                lines.append(
                    f'      call c_f_pointer(src, src_arr, '
                    f'[{cf_shape}])')
                lines.append(
                    f'      obj%{mname} = src_arr')
                lines.append(f'    end if')
                lines.append(
                    f'  end subroutine f2py_set_{typename}_{mname}')
                lines.append('')
                continue

            if _is_pointer_member(mvar):
                isoc_type = _get_member_isoc_type(mvar)
                if isoc_type is None:
                    continue
                ndim = _get_pointer_ndim(mvar)

                # _associated: returns logical(c_bool)
                # F2018 16.9.16: ASSOCIATED intrinsic
                lines.append(
                    f'  function f2py_get_{typename}_{mname}'
                    f'_associated(cptr) '
                    f'result(is_assoc) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    logical(c_bool) :: is_assoc')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    is_assoc = associated(obj%{mname})')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}'
                    f'_associated')
                lines.append('')

                # _ndim: returns compile-time rank
                lines.append(
                    f'  function f2py_get_{typename}_{mname}'
                    f'_ndim(cptr) '
                    f'result(array_rank) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    integer(c_int) :: array_rank')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    array_rank = {ndim}')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}'
                    f'_ndim')
                lines.append('')

                # _shape: fills shape array with size per dimension
                # F2018 16.9.182: SIZE intrinsic
                lines.append(
                    f'  subroutine f2py_get_{typename}_{mname}'
                    f'_shape(cptr, shape_out) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(
                    f'    integer(c_int) :: shape_out({ndim})')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    if (associated(obj%{mname})) then')
                for dim_idx in range(1, ndim + 1):
                    lines.append(
                        f'      shape_out({dim_idx}) = '
                        f'size(obj%{mname}, {dim_idx})')
                lines.append(f'    else')
                for dim_idx in range(1, ndim + 1):
                    lines.append(
                        f'      shape_out({dim_idx}) = 0')
                lines.append(f'    end if')
                lines.append(
                    f'  end subroutine f2py_get_{typename}_{mname}'
                    f'_shape')
                lines.append('')

                # _data: returns c_loc of pointer target
                # F2018 18.2.3.3: C_LOC argument constraints
                # Pointer targets must have the TARGET attribute
                # or be pointer-associated (F2018 10.2.2.2)
                lines.append(
                    f'  function f2py_get_{typename}_{mname}'
                    f'_data(cptr) '
                    f'result(data_ptr) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(f'    type(c_ptr) :: data_ptr')
                lines.append(
                    f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(
                    f'    if (associated(obj%{mname})) then')
                lines.append(
                    f'      data_ptr = c_loc(obj%{mname})')
                lines.append(f'    else')
                lines.append(f'      data_ptr = c_null_ptr')
                lines.append(f'    end if')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}'
                    f'_data')
                lines.append('')
                # No setter for pointer members -- pointer association
                # from C would require the target to have TARGET
                # attribute and lifetime management (F2018 10.2.2)
                continue

            isoc_type = _get_member_isoc_type(mvar)
            if isoc_type is None:
                continue
            dims = _get_array_dims(mvar)

            if dims:
                # Array getter: returns c_ptr to array data via c_loc
                total = 1
                for d in dims:
                    total *= d
                dim_str = ', '.join(str(d) for d in dims)

                lines.append(
                    f'  function f2py_get_{typename}_{mname}(cptr) '
                    f'result(arrptr) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(f'    type(c_ptr) :: arrptr')
                lines.append(f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(f'    arrptr = c_loc(obj%{mname})')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}')
                lines.append('')

                # Array setter: accepts pointer to array data, copies in
                lines.append(
                    f'  subroutine f2py_set_{typename}_{mname}'
                    f'(cptr, arr) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(f'    {isoc_type}, intent(in) :: arr({total})')
                lines.append(f'    type({typename}), pointer :: obj')
                lines.append(f'    integer :: i')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                # Reshape from flat array into member shape
                if len(dims) == 1:
                    lines.append(f'    obj%{mname} = arr')
                else:
                    lines.append(
                        f'    obj%{mname} = reshape(arr, (/{dim_str}/))')
                lines.append(
                    f'  end subroutine f2py_set_{typename}_{mname}')
                lines.append('')
            else:
                # Scalar getter
                lines.append(
                    f'  function f2py_get_{typename}_{mname}(cptr) '
                    f'result(val) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(f'    {isoc_type} :: val')
                lines.append(f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(f'    val = obj%{mname}')
                lines.append(
                    f'  end function f2py_get_{typename}_{mname}')
                lines.append('')

                # Scalar setter
                lines.append(
                    f'  subroutine f2py_set_{typename}_{mname}'
                    f'(cptr, val) bind(c)')
                lines.append(f'    type(c_ptr), value :: cptr')
                lines.append(f'    {isoc_type}, value :: val')
                lines.append(f'    type({typename}), pointer :: obj')
                lines.append(f'    call c_f_pointer(cptr, obj)')
                lines.append(f'    obj%{mname} = val')
                lines.append(
                    f'  end subroutine f2py_set_{typename}_{mname}')
                lines.append('')

    # Add routine wrappers
    for wrapper_code in routine_wrappers:
        lines.append(wrapper_code)

    # Add operator wrappers
    lines.extend(operator_wrappers)

    lines.append(f'end module f2py_{modulename}_derived_wrappers')
    lines.append('')

    return '\n'.join(lines)


def write_fortran_wrappers(buildpath, modulename, type_blocks,
                           routines=None, module_block=None):
    """Write Fortran wrapper file if opaque types or wrapped routines exist.

    Returns the filename if written, None otherwise.
    """
    source = generate_fortran_wrappers(modulename, type_blocks,
                                       routines=routines,
                                       module_block=module_block)
    if source is None:
        return None

    fname = f'{modulename}-f2pyderivedwrappers.f90'
    fpath = os.path.join(buildpath, fname)
    with open(fpath, 'w') as f:
        f.write(source)
    outmess(f'\tFortran derived type wrappers saved to "{fpath}"\n')
    return fname


# --- Feature 4: Derived type arguments in routines ---

def _is_array_type_arg(var):
    """Check if a variable is an array of a derived type."""
    return (var.get('typespec') == 'type'
            and 'dimension' in var
            and len(var['dimension']) > 0)


def _has_derived_type_args(routine):
    """Check if a routine has any derived type arguments or returns one."""
    for argname in routine.get('args', []):
        var = routine['vars'].get(argname, {})
        if var.get('typespec') == 'type':
            return True
    if isfunction(routine):
        result_var = routine.get('result', routine['name'])
        rvar = routine['vars'].get(result_var, {})
        if rvar.get('typespec') == 'type':
            return True
    return False


def _get_wrappable_routines(module, type_map):
    """Find routines with derived type args where all types are wrappable.

    type_map: dict mapping typename -> typeblock for wrappable types.
    Returns list of routine blocks.
    """
    if not hasbody(module):
        return []
    result = []
    for b in module['body']:
        if not isroutine(b):
            continue
        if not _has_derived_type_args(b):
            continue
        # Check all derived type args reference wrappable types
        all_ok = True
        for argname in b.get('args', []):
            var = b['vars'].get(argname, {})
            if var.get('typespec') == 'type':
                tname = var.get('typename', '').lower()
                if tname not in type_map:
                    all_ok = False
                    break
        # Check function return type
        if all_ok and isfunction(b):
            result_var = b.get('result', b['name'])
            rvar = b['vars'].get(result_var, {})
            if rvar.get('typespec') == 'type':
                tname = rvar.get('typename', '').lower()
                if tname not in type_map:
                    all_ok = False
        if all_ok:
            result.append(b)
    return result


def _gen_routine_fortran_wrapper(modulename, routine, type_map):
    """Generate Fortran bind(c) wrapper for a routine with derived type args.

    The wrapper accepts void* (c_ptr) for each derived type argument,
    converts via c_f_pointer, and calls the original routine.
    """
    rname = routine['name']
    is_func = isfunction(routine)
    args = routine.get('args', [])

    wrapper_name = f'f2py_wrap_{rname}'
    wrapper_args = []
    decls = []
    local_decls = []
    pre_call = []
    post_call = []
    call_args = []

    result_var = None
    result_type = None
    returns_type = False
    if is_func:
        result_var = routine.get('result', rname)
        rvar = routine['vars'].get(result_var, {})
        if rvar.get('typespec') == 'type':
            returns_type = True
            result_type = 'type'
            tname_ret = rvar.get('typename', '').lower()
            local_decls.append(
                f'    type({tname_ret}), pointer :: f2py_temp_result')
        else:
            result_type = rvar.get('typespec', '')

    for argname in args:
        var = routine['vars'].get(argname, {})
        if var.get('typespec') == 'type' and _is_array_type_arg(var):
            tname = var.get('typename', '').lower()
            dim_expr = var['dimension'][0]
            intent = var.get('intent', [])
            if 'out' in intent and isallocatable(var):
                # Intent(out) allocatable array of derived type
                # Fortran allocates; we extract heap copies post-call
                wrapper_args.append(f'{argname}_ptrs')
                wrapper_args.append(f'{argname}_n')
                decls.append(
                    f'    type(c_ptr) :: {argname}_ptrs(*)')
                decls.append(
                    f'    integer(c_int) :: {argname}_n')
                local_decls.append(
                    f'    type({tname}), allocatable :: {argname}(:)')
                local_decls.append(
                    f'    type({tname}), pointer :: {argname}_heap_tmp')
                local_decls.append(f'    integer :: {argname}_i')
                # Post-call: extract each element as heap copy
                post_call.append(
                    f'    {argname}_n = size({argname})')
                post_call.append(
                    f'    do {argname}_i = 1, {argname}_n')
                post_call.append(
                    f'      allocate({argname}_heap_tmp)')
                post_call.append(
                    f'      {argname}_heap_tmp = '
                    f'{argname}({argname}_i)')
                post_call.append(
                    f'      {argname}_ptrs({argname}_i) = '
                    f'c_loc({argname}_heap_tmp)')
                post_call.append(
                    f'    end do')
                call_args.append(argname)
            else:
                # Input array of derived type argument
                wrapper_args.append(f'{argname}_ptrs')
                wrapper_args.append(f'{argname}_n')
                decls.append(
                    f'    type(c_ptr), intent(in) :: {argname}_ptrs(*)')
                decls.append(
                    f'    integer(c_int), value :: {argname}_n')
                local_decls.append(
                    f'    type({tname}), pointer :: {argname}_tmp')
                local_decls.append(
                    f'    type({tname}), allocatable :: {argname}(:)')
                local_decls.append(f'    integer :: {argname}_i')
                pre_call.append(
                    f'    allocate({argname}({argname}_n))')
                pre_call.append(
                    f'    do {argname}_i = 1, {argname}_n')
                pre_call.append(
                    f'      call c_f_pointer('
                    f'{argname}_ptrs({argname}_i), {argname}_tmp)')
                pre_call.append(
                    f'      {argname}({argname}_i) = {argname}_tmp')
                pre_call.append(
                    f'    end do')
                call_args.append(argname)
            # Skip the corresponding size arg from regular processing
            # by noting the dimension expression
        elif var.get('typespec') == 'type':
            tname = var.get('typename', '').lower()
            wrapper_args.append(f'{argname}_ptr')
            decls.append(f'    type(c_ptr), value :: {argname}_ptr')
            local_decls.append(
                f'    type({tname}), pointer :: {argname}')
            intent = var.get('intent', [])
            if 'out' in intent:
                # For intent(out), allocate a new one, call, return ptr
                pre_call.append(f'    allocate({argname})')
                post_call.append(
                    f'    {argname}_ptr = c_loc({argname})')
                # Rewrite decl: _ptr is inout (returns updated ptr)
                decls[-1] = f'    type(c_ptr) :: {argname}_ptr'
            else:
                pre_call.append(
                    f'    call c_f_pointer({argname}_ptr, {argname})')
            call_args.append(argname)
        else:
            # Scalar arg -- pass through
            isoc_type = _get_member_isoc_type(var)
            if isoc_type is None:
                return None, None
            wrapper_args.append(argname)
            intent = var.get('intent', [])
            if 'out' in intent or 'inout' in intent:
                decls.append(f'    {isoc_type} :: {argname}')
            else:
                decls.append(f'    {isoc_type}, value :: {argname}')
            call_args.append(argname)

    wrapper_args_str = ', '.join(wrapper_args)
    decls_str = '\n'.join(decls)
    local_decls_str = '\n'.join(local_decls)
    pre_call_str = '\n'.join(pre_call)
    post_call_str = '\n'.join(post_call)
    call_args_str = ', '.join(call_args)

    lines = []
    if is_func:
        if returns_type:
            lines.append(
                f'  function {wrapper_name}({wrapper_args_str}) '
                f'result(retval) bind(c)')
            lines.append(f'    type(c_ptr) :: retval')
        else:
            # Function returning scalar
            ret_isoc = _get_member_isoc_type(
                routine['vars'].get(result_var, {}))
            if ret_isoc is None:
                return None, None
            lines.append(
                f'  function {wrapper_name}({wrapper_args_str}) '
                f'result(retval) bind(c)')
            lines.append(f'    {ret_isoc} :: retval')
    else:
        lines.append(
            f'  subroutine {wrapper_name}({wrapper_args_str}) bind(c)')

    lines.append(decls_str)
    if local_decls_str:
        lines.append(local_decls_str)
    if pre_call_str:
        lines.append(pre_call_str)

    if is_func:
        if returns_type:
            lines.append(f'    allocate(f2py_temp_result)')
            lines.append(
                f'    f2py_temp_result = {rname}({call_args_str})')
            lines.append(f'    retval = c_loc(f2py_temp_result)')
        else:
            lines.append(
                f'    retval = {rname}({call_args_str})')
    else:
        lines.append(f'    call {rname}({call_args_str})')

    if post_call_str:
        lines.append(post_call_str)

    if is_func:
        lines.append(f'  end function {wrapper_name}')
    else:
        lines.append(f'  end subroutine {wrapper_name}')
    lines.append('')

    return wrapper_name, '\n'.join(lines)


def _gen_routine_c_wrapper(modulename, routine, type_map):
    """Generate C wrapper function for a routine with derived type args.

    Returns (c_code, method_def_entry) or (None, None) if not wrappable.
    """
    rname = routine['name']
    is_func = isfunction(routine)
    args = routine.get('args', [])
    wrapper_sym = f'f2py_wrap_{rname}'

    # Build extern declaration
    extern_args = []
    # Track which scalar args are consumed as array size parameters
    array_size_args = set()
    for argname in args:
        var = routine['vars'].get(argname, {})
        if _is_array_type_arg(var):
            # The dimension expression names the size arg
            dim_expr = var['dimension'][0]
            # Assumed-shape (:) has no named size variable
            if dim_expr != ':':
                array_size_args.add(dim_expr.lower())

    for argname in args:
        var = routine['vars'].get(argname, {})
        if _is_array_type_arg(var):
            intent = var.get('intent', [])
            extern_args.append('void **')
            if 'out' in intent and isallocatable(var):
                # Intent(out): count is passed by reference (inout)
                extern_args.append('int *')
            else:
                extern_args.append('int')
        elif var.get('typespec') == 'type':
            intent = var.get('intent', [])
            if 'out' in intent:
                extern_args.append('void **')
            else:
                extern_args.append('void *')
        elif argname.lower() in array_size_args:
            # Size arg consumed by array-of-type; still passed to Fortran
            ctype = _get_member_ctype(var)
            if ctype is None:
                return None, None
            extern_args.append(ctype)
        else:
            ctype = _get_member_ctype(var)
            if ctype is None:
                return None, None
            intent = var.get('intent', [])
            if 'out' in intent or 'inout' in intent:
                extern_args.append(f'{ctype} *')
            else:
                extern_args.append(ctype)

    result_var = None
    result_ctype = None
    returns_type_name = None
    if is_func:
        result_var = routine.get('result', rname)
        rvar = routine['vars'].get(result_var, {})
        if rvar.get('typespec') == 'type':
            returns_type_name = rvar.get('typename', '').lower()
            extern_ret = 'void *'
        else:
            result_ctype = _get_member_ctype(rvar)
            if result_ctype is None:
                return None, None
            extern_ret = result_ctype
    else:
        extern_ret = 'void'

    extern_args_str = ', '.join(extern_args) if extern_args else 'void'
    extern_line = f'extern {extern_ret} {wrapper_sym}({extern_args_str});'

    # Build Python wrapper function
    lines = []
    lines.append(extern_line)
    lines.append('')
    lines.append(f'static PyObject *')
    lines.append(
        f'f2py_routine_{rname}(PyObject *self, PyObject *args, '
        f'PyObject *kwds)')
    lines.append('{')

    # Build kwlist and format string
    kwlist = []
    fmt_parts = []
    parse_args_decl = []
    parse_args_ref = []
    call_parts = []

    for argname in args:
        var = routine['vars'].get(argname, {})
        if _is_array_type_arg(var):
            tname = var.get('typename', '').lower()
            intent = var.get('intent', [])
            if 'out' in intent and isallocatable(var):
                # Intent(out) allocatable array of type: output only
                # No Python input needed; handled post-call
                pass
            else:
                # Input array of derived type: accept Python list
                kwlist.append(argname)
                fmt_parts.append('O')
                parse_args_decl.append(
                    f'    PyObject *{argname}_list = NULL;')
                parse_args_ref.append(f'&{argname}_list')
        elif var.get('typespec') == 'type':
            tname = var.get('typename', '').lower()
            intent = var.get('intent', [])
            kwlist.append(argname)
            if 'out' in intent:
                # intent(out) type arg: not passed from Python
                # Actually we still need to pass something -- allocate on
                # Fortran side. Skip from Python args; handled separately.
                kwlist.pop()  # remove from kwlist
                continue
            fmt_parts.append('O')
            parse_args_decl.append(f'    PyObject *{argname}_obj = NULL;')
            parse_args_ref.append(f'&{argname}_obj')
        elif argname.lower() in array_size_args:
            # Size arg consumed by array-of-type; derived from list length
            ctype = _get_member_ctype(var)
            parse_args_decl.append(f'    {ctype} {argname} = 0;')
            # Do NOT add to kwlist/fmt/refs -- computed from list length
        else:
            ctype = _get_member_ctype(var)
            fmt = _C_TO_PYFORMAT.get(ctype)
            if fmt is None:
                return None, None
            intent = var.get('intent', [])
            kwlist.append(argname)
            if 'out' in intent:
                # Skip from Python args for intent(out) scalars
                kwlist.pop()
                fmt_parts.append('')  # placeholder
                parse_args_decl.append(f'    {ctype} {argname} = 0;')
                continue
            fmt_parts.append(fmt)
            parse_args_decl.append(f'    {ctype} {argname} = 0;')
            parse_args_ref.append(f'&{argname}')

    kwlist_str = ', '.join(f'"{k}"' for k in kwlist)
    fmt_str = '|' + ''.join(fmt_parts)
    parse_args_str = ', '.join(parse_args_ref)

    for decl in parse_args_decl:
        lines.append(decl)
    lines.append('')

    if kwlist:
        lines.append(
            f'    static char *kwlist[] = {{{kwlist_str}, NULL}};')
        lines.append(
            f'    if (!PyArg_ParseTupleAndKeywords(args, kwds, '
            f'"{fmt_str}", kwlist,')
        lines.append(f'                                     {parse_args_str}))')
        lines.append('        return NULL;')
    lines.append('')

    # Extract capsule pointers for type args
    # Track array-of-type args that need cleanup
    array_type_cleanup = []
    # Track intent(out) array-of-type args for post-call list building
    out_array_type_args = []
    for argname in args:
        var = routine['vars'].get(argname, {})
        if _is_array_type_arg(var):
            tname = var.get('typename', '').lower()
            intent = var.get('intent', [])
            if 'out' in intent and isallocatable(var):
                # Intent(out) allocatable array of type
                # Allocate buffer for Fortran to fill with pointers
                lines.append(
                    f'    void *{argname}_ptrs[4096];')
                lines.append(
                    f'    int {argname}_n = 0;')
                out_array_type_args.append((argname, tname))
            else:
                capsule_name = f'f2py.{tname}'
                dim_expr = var['dimension'][0].lower()
                lines.append(
                    f'    if ({argname}_list == NULL || '
                    f'!PyList_Check({argname}_list)) {{')
                lines.append(
                    f'        PyErr_SetString(PyExc_TypeError, '
                    f'"{argname} must be a list of {tname} instances");')
                lines.append('        return NULL;')
                lines.append('    }')
                lines.append(
                    f'    Py_ssize_t {argname}_len = '
                    f'PyList_GET_SIZE({argname}_list);')
                # Set the size arg from the list length
                # (skip for assumed-shape ':' -- no named size variable)
                if dim_expr != ':':
                    lines.append(
                        f'    {dim_expr} = (int){argname}_len;')
                lines.append(
                    f'    void **{argname}_ptrs = (void **)malloc('
                    f'sizeof(void *) * {argname}_len);')
                lines.append(
                    f'    if ({argname}_ptrs == NULL) {{')
                lines.append(
                    f'        PyErr_NoMemory();')
                lines.append('        return NULL;')
                lines.append('    }')
                lines.append(
                    f'    for (Py_ssize_t _i = 0; '
                    f'_i < {argname}_len; _i++) {{')
                lines.append(
                    f'        PyObject *_item = '
                    f'PyList_GET_ITEM({argname}_list, _i);')
                lines.append(
                    f'        if (!Py_IS_TYPE(_item, '
                    f'&Py{tname}_Type)) {{')
                lines.append(
                    f'            free({argname}_ptrs);')
                lines.append(
                    f'            PyErr_SetString(PyExc_TypeError, '
                    f'"{argname} items must be {tname} instances");')
                lines.append('            return NULL;')
                lines.append('        }')
                lines.append(
                    f'        Py{tname}Object *_typed = '
                    f'(Py{tname}Object *)_item;')
                lines.append(
                    f'        if (_typed->capsule == NULL) {{')
                lines.append(
                    f'            free({argname}_ptrs);')
                lines.append(
                    f'            PyErr_SetString(PyExc_RuntimeError, '
                    f'"{argname} item not initialized");')
                lines.append('            return NULL;')
                lines.append('        }')
                lines.append(
                    f'        {argname}_ptrs[_i] = PyCapsule_GetPointer('
                    f'_typed->capsule, "{capsule_name}");')
                lines.append(
                    f'        if ({argname}_ptrs[_i] == NULL) {{')
                lines.append(
                    f'            free({argname}_ptrs);')
                lines.append('            return NULL;')
                lines.append('        }')
                lines.append('    }')
                array_type_cleanup.append(f'{argname}_ptrs')
        elif var.get('typespec') == 'type':
            tname = var.get('typename', '').lower()
            intent = var.get('intent', [])
            capsule_name = f'f2py.{tname}'
            if 'out' in intent:
                lines.append(f'    void *{argname}_ptr = NULL;')
            else:
                lines.append(
                    f'    if ({argname}_obj == NULL) {{')
                lines.append(
                    f'        PyErr_SetString(PyExc_TypeError, '
                    f'"{argname} is required");')
                lines.append('        return NULL;')
                lines.append('    }')
                # Check it's the right type
                lines.append(
                    f'    if (!Py_IS_TYPE({argname}_obj, '
                    f'&Py{tname}_Type)) {{')
                lines.append(
                    f'        PyErr_SetString(PyExc_TypeError, '
                    f'"{argname} must be a {tname} instance");')
                lines.append('        return NULL;')
                lines.append('    }')
                lines.append(
                    f'    Py{tname}Object *{argname}_typed = '
                    f'(Py{tname}Object *){argname}_obj;')
                lines.append(
                    f'    if ({argname}_typed->capsule == NULL) {{')
                lines.append(
                    f'        PyErr_SetString(PyExc_RuntimeError, '
                    f'"{argname} not initialized");')
                lines.append('        return NULL;')
                lines.append('    }')
                lines.append(
                    f'    void *{argname}_ptr = PyCapsule_GetPointer('
                    f'{argname}_typed->capsule, "{capsule_name}");')
                lines.append(
                    f'    if ({argname}_ptr == NULL) return NULL;')
    lines.append('')

    # Build call
    call_args = []
    for argname in args:
        var = routine['vars'].get(argname, {})
        if _is_array_type_arg(var):
            intent = var.get('intent', [])
            if 'out' in intent and isallocatable(var):
                # Intent(out): pass buffer + pointer to count
                call_args.append(f'{argname}_ptrs')
                call_args.append(f'&{argname}_n')
            else:
                # Input: pass void** array and int count
                call_args.append(f'{argname}_ptrs')
                call_args.append(f'(int){argname}_len')
        elif var.get('typespec') == 'type':
            intent = var.get('intent', [])
            if 'out' in intent:
                call_args.append(f'&{argname}_ptr')
            else:
                call_args.append(f'{argname}_ptr')
        elif argname.lower() in array_size_args:
            # Size arg -- pass the value derived from list length
            call_args.append(argname)
        else:
            intent = var.get('intent', [])
            if 'out' in intent or 'inout' in intent:
                call_args.append(f'&{argname}')
            else:
                call_args.append(argname)

    call_args_str = ', '.join(call_args)

    if is_func:
        if returns_type_name:
            tname = returns_type_name
            capsule_name = f'f2py.{tname}'
            lines.append(
                f'    void *result = {wrapper_sym}({call_args_str});')
            for cleanup_var in array_type_cleanup:
                lines.append(f'    free({cleanup_var});')
            lines.append(f'    if (result == NULL) {{')
            lines.append(
                f'        PyErr_SetString(PyExc_RuntimeError, '
                f'"Fortran function returned NULL");')
            lines.append('        return NULL;')
            lines.append('    }')
            lines.append(
                f'    Py{tname}Object *out = (Py{tname}Object *)'
                f'Py{tname}_Type.tp_alloc(&Py{tname}_Type, 0);')
            lines.append('    if (out == NULL) return NULL;')
            lines.append(
                f'    out->capsule = PyCapsule_New('
                f'result, "{capsule_name}", '
                f'f2py_{tname}_capsule_destructor);')
            lines.append(
                '    if (out->capsule == NULL) { '
                'Py_DECREF(out); return NULL; }')
            lines.append('    return (PyObject *)out;')
        else:
            lines.append(
                f'    {result_ctype} result = '
                f'{wrapper_sym}({call_args_str});')
            # Free array-of-type temporary arrays
            for cleanup_var in array_type_cleanup:
                lines.append(f'    free({cleanup_var});')
            # Convert result to PyObject
            pyobj_expr = _C_TO_PYOBJ.get(result_ctype)
            if pyobj_expr:
                lines.append(
                    f'    return {pyobj_expr.format(val="result")};')
            else:
                lines.append('    Py_RETURN_NONE;')
    else:
        lines.append(f'    {wrapper_sym}({call_args_str});')
        # Free array-of-type temporary arrays
        for cleanup_var in array_type_cleanup:
            lines.append(f'    free({cleanup_var});')

        # Build return value -- collect intent(out) and intent(inout) args
        out_parts = []
        for argname in args:
            var = routine['vars'].get(argname, {})
            intent = var.get('intent', [])
            if (_is_array_type_arg(var) and 'out' in intent
                    and isallocatable(var)):
                tname = var.get('typename', '').lower()
                out_parts.append((argname, 'type_array', tname))
            elif var.get('typespec') == 'type' and 'out' in intent:
                tname = var.get('typename', '').lower()
                out_parts.append((argname, 'type', tname))
            elif 'out' in intent or 'inout' in intent:
                ctype = _get_member_ctype(var)
                out_parts.append((argname, 'scalar', ctype))

        if not out_parts:
            lines.append('    Py_RETURN_NONE;')
        else:
            # Helper: emit code for a single out_part into `lines`
            def _emit_out_part(aname, kind, info, var_suffix=''):
                """Emit lines to build a PyObject for one output part.

                var_suffix: suffix for local variable names (e.g. '0')
                Returns the variable name holding the PyObject*.
                """
                if kind == 'scalar':
                    pyobj_expr = _C_TO_PYOBJ.get(info)
                    if pyobj_expr:
                        vname = f'out_val{var_suffix}'
                        lines.append(
                            f'    PyObject *{vname} = '
                            f'{pyobj_expr.format(val=aname)};')
                        return vname
                    return None
                elif kind == 'type':
                    tname = info
                    capsule_name = f'f2py.{tname}'
                    vname = f'out{var_suffix}'
                    lines.append(
                        f'    Py{tname}Object *{vname} = '
                        f'(Py{tname}Object *)'
                        f'Py{tname}_Type.tp_alloc('
                        f'&Py{tname}_Type, 0);')
                    lines.append(
                        f'    if ({vname} == NULL) return NULL;')
                    lines.append(
                        f'    {vname}->capsule = PyCapsule_New('
                        f'{aname}_ptr, "{capsule_name}", '
                        f'f2py_{tname}_capsule_destructor);')
                    lines.append(
                        f'    if ({vname}->capsule == NULL) {{ '
                        f'Py_DECREF({vname}); return NULL; }}')
                    return f'(PyObject *){vname}'
                elif kind == 'type_array':
                    tname = info
                    capsule_name = f'f2py.{tname}'
                    vname = f'out_list{var_suffix}'
                    lines.append(
                        f'    PyObject *{vname} = '
                        f'PyList_New({aname}_n);')
                    lines.append(
                        f'    if ({vname} == NULL) return NULL;')
                    lines.append(
                        f'    for (int _j = 0; '
                        f'_j < {aname}_n; _j++) {{')
                    lines.append(
                        f'        Py{tname}Object *_item = '
                        f'(Py{tname}Object *)'
                        f'Py{tname}_Type.tp_alloc('
                        f'&Py{tname}_Type, 0);')
                    lines.append(
                        f'        if (_item == NULL) {{ '
                        f'Py_DECREF({vname}); return NULL; }}')
                    lines.append(
                        f'        _item->capsule = PyCapsule_New('
                        f'{aname}_ptrs[_j], "{capsule_name}", '
                        f'f2py_{tname}_capsule_destructor);')
                    lines.append(
                        f'        if (_item->capsule == NULL) {{ '
                        f'Py_DECREF(_item); Py_DECREF({vname}); '
                        f'return NULL; }}')
                    lines.append(
                        f'        PyList_SET_ITEM({vname}, _j, '
                        f'(PyObject *)_item);')
                    lines.append('    }')
                    return vname
                return None

            if len(out_parts) == 1:
                aname, kind, info = out_parts[0]
                result_var_name = _emit_out_part(aname, kind, info)
                if result_var_name:
                    lines.append(
                        f'    return {result_var_name};')
                else:
                    lines.append('    Py_RETURN_NONE;')
            else:
                # Multiple outputs -- return tuple
                lines.append(
                    f'    PyObject *ret = '
                    f'PyTuple_New({len(out_parts)});')
                lines.append(
                    '    if (ret == NULL) return NULL;')
                for i, (aname, kind, info) in enumerate(out_parts):
                    result_var_name = _emit_out_part(
                        aname, kind, info, var_suffix=str(i))
                    if result_var_name:
                        lines.append(
                            f'    PyTuple_SET_ITEM(ret, {i}, '
                            f'{result_var_name});')
                lines.append('    return ret;')

    lines.append('}')
    lines.append('')

    c_code = '\n'.join(lines)

    # Method definition entry
    method_def = (
        f'    {{"{rname}", (PyCFunction)f2py_routine_{rname}, '
        f'METH_VARARGS | METH_KEYWORDS, '
        f'"Wrapper for Fortran routine {rname}"}},'
    )

    return c_code, method_def


def _scan_type_bound_procedures(source_file, typename):
    """Scan Fortran source for type-bound procedure declarations.

    Returns a dict mapping method_name -> impl_name from lines like:
        procedure :: method => impl
        procedure :: method  (impl == method when no =>)
    within the 'contains' section of the named type block.
    """
    import re
    result = {}
    if not source_file or not os.path.isfile(source_file):
        return result

    in_type = False
    in_contains = False
    type_pat = re.compile(
        r'^\s*type\b(?:\s*,\s*\w+)*\s*::\s*' + re.escape(typename),
        re.I)
    end_type_pat = re.compile(
        r'^\s*end\s+type\b', re.I)
    contains_pat = re.compile(r'^\s*contains\b', re.I)
    proc_pat = re.compile(
        r'^\s*procedure\s*::\s*(\w+)\s*(?:=>\s*(\w+))?\s*$', re.I)
    # F2018 7.5.5 paragraph 3, R751:
    # GENERIC [ , access-spec ] :: generic-spec => binding-name-list
    # Maps a generic name to multiple specific procedures.
    # We use the first specific binding as the implementation.
    generic_pat = re.compile(
        r'^\s*generic\s*(?:,\s*\w+)?\s*::\s*(\w+)\s*=>\s*(.+)\s*$',
        re.I)

    with open(source_file) as f:
        for line in f:
            stripped = line.split('!')[0].strip()  # remove comments
            if not stripped:
                continue
            if not in_type:
                if type_pat.match(stripped):
                    in_type = True
                continue
            if end_type_pat.match(stripped):
                break
            if contains_pat.match(stripped):
                in_contains = True
                continue
            if in_contains:
                m = proc_pat.match(stripped)
                if m:
                    method_name = m.group(1).lower()
                    impl_name = (m.group(2) or m.group(1)).lower()
                    result[method_name] = impl_name
                    continue
                # Generic bindings (F2018 R751): use first specific
                # binding as implementation. Type dispatch from Python
                # is not supported -- the first implementation is used.
                generic_match = generic_pat.match(stripped)
                if generic_match:
                    generic_name = generic_match.group(1).lower()
                    bindings = [
                        binding.strip().lower()
                        for binding in generic_match.group(2).split(',')
                    ]
                    if bindings:
                        # Map generic name to first specific binding
                        result[generic_name] = bindings[0]

    return result


def _scan_final_subroutines(source_file, typename):
    """Scan Fortran source for FINAL subroutine declarations in a type.

    Returns a set of lowercased final subroutine names from lines like:
        final :: sub1, sub2
    within the 'contains' section of the named type block.

    F2018 7.5.6.1 (R753): FINAL [ :: ] final-subroutine-name-list
    """
    import re
    result = set()
    if not source_file or not os.path.isfile(source_file):
        return result

    in_type = False
    in_contains = False
    type_pat = re.compile(
        r'^\s*type\b(?:\s*,\s*\w+)*\s*::\s*' + re.escape(typename),
        re.I)
    end_type_pat = re.compile(
        r'^\s*end\s+type\b', re.I)
    contains_pat = re.compile(r'^\s*contains\b', re.I)
    final_pat = re.compile(
        r'^\s*final\s*(?:::)?\s*(.+)\s*$', re.I)

    with open(source_file) as f:
        for line in f:
            stripped = line.split('!')[0].strip()
            if not stripped:
                continue
            if not in_type:
                if type_pat.match(stripped):
                    in_type = True
                continue
            if end_type_pat.match(stripped):
                break
            if contains_pat.match(stripped):
                in_contains = True
                continue
            if in_contains:
                final_match = final_pat.match(stripped)
                if final_match:
                    names = final_match.group(1)
                    for name in names.split(','):
                        name = name.strip().lower()
                        if name:
                            result.add(name)

    return result


def _gen_type_methods(typename, bound_procs, routines, type_map):
    """Generate PyMethodDef entries and C method functions for type-bound
    procedures.

    Each method is a thin wrapper that calls the already-generated
    module-level routine wrapper, automatically passing 'self' as the
    first (derived type) argument.
    """
    funcs = []
    method_entries = []

    # Build lookup from routine name to routine block
    routine_map = {}
    for r in routines:
        routine_map[r['name'].lower()] = r

    for method_name, impl_name in bound_procs.items():
        # Resolve binding chain: generic bindings map to specific
        # binding names (F2018 7.5.5 R751), which in turn map to
        # implementation names. Follow the chain until we find an
        # actual module routine.
        resolved_name = impl_name
        max_chain_depth = 5  # prevent infinite loops
        for _ in range(max_chain_depth):
            if resolved_name in routine_map:
                break
            # Check if this is itself a binding name
            next_name = bound_procs.get(resolved_name)
            if next_name is None or next_name == resolved_name:
                break
            resolved_name = next_name
        routine = routine_map.get(resolved_name)
        if routine is None:
            continue

        args = routine.get('args', [])
        if not args:
            continue

        # First arg should be the self/this type arg
        self_arg = args[0]
        self_var = routine['vars'].get(self_arg, {})
        if self_var.get('typespec') != 'type':
            continue

        # Remaining args (non-self)
        other_args = args[1:]

        # Generate a C method that takes the type instance as self
        # and remaining args as positional/keyword args
        is_func = isfunction(routine)
        # Use resolved_name for the wrapper symbol since that is the
        # actual module routine whose C wrapper was generated
        wrapper_sym = f'f2py_wrap_{resolved_name}'

        # Generate extern declaration for the Fortran wrapper
        extern_args = []
        for argname in args:
            var = routine['vars'].get(argname, {})
            if var.get('typespec') == 'type':
                intent = var.get('intent', [])
                if 'out' in intent:
                    extern_args.append('void **')
                else:
                    extern_args.append('void *')
            else:
                ctype = _get_member_ctype(var)
                if ctype is None:
                    break
                intent = var.get('intent', [])
                if 'out' in intent or 'inout' in intent:
                    extern_args.append(f'{ctype} *')
                else:
                    extern_args.append(ctype)

        if is_func:
            result_var = routine.get('result', impl_name)
            rvar = routine['vars'].get(result_var, {})
            result_ctype = _get_member_ctype(rvar)
            extern_ret = result_ctype if result_ctype else 'void'
        else:
            extern_ret = 'void'

        extern_args_str = (', '.join(extern_args)
                           if extern_args else 'void')

        # Build the method C function
        mfunc_name = f'Py{typename}_method_{method_name}'
        lines = []
        lines.append(
            f'extern {extern_ret} {wrapper_sym}({extern_args_str});')
        lines.append('')
        lines.append(f'static PyObject *')
        lines.append(
            f'{mfunc_name}(PyObject *selfobj, PyObject *args, '
            f'PyObject *kwds)')
        lines.append('{')
        lines.append(
            f'    Py{typename}Object *self = '
            f'(Py{typename}Object *)selfobj;')

        capsule_name = f'f2py.{typename.lower()}'
        lines.append(f'    if (self->capsule == NULL) {{')
        lines.append(
            f'        PyErr_SetString(PyExc_RuntimeError, '
            f'"{typename} not initialized");')
        lines.append('        return NULL;')
        lines.append('    }')
        lines.append(
            f'    void *self_ptr = PyCapsule_GetPointer('
            f'self->capsule, "{capsule_name}");')
        lines.append('    if (self_ptr == NULL) return NULL;')
        lines.append('')

        # Parse remaining args
        kwlist = []
        fmt_parts = []
        parse_decls = []
        parse_refs = []
        call_args = ['self_ptr']

        for argname in other_args:
            var = routine['vars'].get(argname, {})
            if var.get('typespec') == 'type':
                tname = var.get('typename', '').lower()
                intent = var.get('intent', [])
                if 'out' in intent:
                    call_args.append(f'&{argname}_ptr')
                    lines.append(f'    void *{argname}_ptr = NULL;')
                    continue
                kwlist.append(argname)
                fmt_parts.append('O')
                parse_decls.append(
                    f'    PyObject *{argname}_obj = NULL;')
                parse_refs.append(f'&{argname}_obj')
                # Will extract pointer below
            else:
                ctype = _get_member_ctype(var)
                fmt = _C_TO_PYFORMAT.get(ctype)
                if fmt is None:
                    break  # skip this method
                intent = var.get('intent', [])
                if 'out' in intent:
                    parse_decls.append(f'    {ctype} {argname} = 0;')
                    call_args.append(f'&{argname}')
                    continue
                kwlist.append(argname)
                fmt_parts.append(fmt)
                parse_decls.append(f'    {ctype} {argname} = 0;')
                parse_refs.append(f'&{argname}')
                intent = var.get('intent', [])
                if 'out' in intent or 'inout' in intent:
                    call_args.append(f'&{argname}')
                else:
                    call_args.append(argname)

        for decl in parse_decls:
            lines.append(decl)

        if kwlist:
            kwlist_str = ', '.join(f'"{k}"' for k in kwlist)
            fmt_str = '|' + ''.join(fmt_parts)
            parse_refs_str = ', '.join(parse_refs)
            lines.append(
                f'    static char *kwlist[] = {{{kwlist_str}, NULL}};')
            lines.append(
                f'    if (!PyArg_ParseTupleAndKeywords(args, kwds, '
                f'"{fmt_str}", kwlist,')
            lines.append(
                f'                                     {parse_refs_str}))')
            lines.append('        return NULL;')
        lines.append('')

        # Extract capsule pointers for type args (non-self)
        for argname in other_args:
            var = routine['vars'].get(argname, {})
            if var.get('typespec') == 'type':
                tname = var.get('typename', '').lower()
                intent = var.get('intent', [])
                if 'out' in intent:
                    continue
                cap_name = f'f2py.{tname}'
                lines.append(
                    f'    if ({argname}_obj == NULL || '
                    f'!Py_IS_TYPE({argname}_obj, &Py{tname}_Type)) {{')
                lines.append(
                    f'        PyErr_SetString(PyExc_TypeError, '
                    f'"{argname} must be a {tname} instance");')
                lines.append('        return NULL;')
                lines.append('    }')
                lines.append(
                    f'    void *{argname}_ptr = PyCapsule_GetPointer('
                    f'((Py{tname}Object *){argname}_obj)->capsule, '
                    f'"{cap_name}");')
                lines.append(
                    f'    if ({argname}_ptr == NULL) return NULL;')
                call_args.append(f'{argname}_ptr')

        call_args_str = ', '.join(call_args)

        if is_func:
            result_var = routine.get('result', impl_name)
            rvar = routine['vars'].get(result_var, {})
            result_ctype = _get_member_ctype(rvar)
            if result_ctype:
                lines.append(
                    f'    {result_ctype} result = '
                    f'{wrapper_sym}({call_args_str});')
                pyobj_expr = _C_TO_PYOBJ.get(result_ctype)
                if pyobj_expr:
                    lines.append(
                        f'    return '
                        f'{pyobj_expr.format(val="result")};')
                else:
                    lines.append('    Py_RETURN_NONE;')
            else:
                lines.append(f'    {wrapper_sym}({call_args_str});')
                lines.append('    Py_RETURN_NONE;')
        else:
            lines.append(f'    {wrapper_sym}({call_args_str});')
            lines.append('    Py_RETURN_NONE;')

        lines.append('}')
        lines.append('')

        funcs.append('\n'.join(lines))
        method_entries.append(
            f'    {{"{method_name}", (PyCFunction){mfunc_name}, '
            f'METH_VARARGS | METH_KEYWORDS, '
            f'"Type-bound procedure {method_name}"}},')

    return funcs, method_entries


def _gen_routine_method_table(modulename, method_entries):
    """Generate PyMethodDef table for wrapped routines."""
    lines = []
    lines.append(
        f'static PyMethodDef f2py_{modulename}_derived_methods[] = {{')
    for entry in method_entries:
        lines.append(entry)
    lines.append('    {NULL, NULL, 0, NULL}')
    lines.append('};')
    return '\n'.join(lines)


def _gen_routine_init_code(modulename, method_entries):
    """Generate module init code to register wrapped routine methods."""
    if not method_entries:
        return []
    lines = []
    lines.append('\t{')
    lines.append(f'\t\tPyMethodDef *mdef = f2py_{modulename}_derived_methods;')
    lines.append('\t\twhile (mdef->ml_name != NULL) {')
    lines.append('\t\t\tPyObject *func = PyCFunction_New(mdef, NULL);')
    lines.append('\t\t\tif (func != NULL) {')
    lines.append('\t\t\t\tPyDict_SetItemString(d, mdef->ml_name, func);')
    lines.append('\t\t\t\tPy_DECREF(func);')
    lines.append('\t\t\t}')
    lines.append('\t\t\tmdef++;')
    lines.append('\t\t}')
    lines.append('\t}')
    return lines
